[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[[edge_functions]]
  path = "/api/analyse"
  function = "analyse"

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/db"
  to = "/.netlify/functions/db-connect"
  status = 200

[[redirects]]
  from = "/api/projects"
  to = "/.netlify/functions/projects"
  status = 200