/* scripts/build-routes.js — generate public/_redirects from the pages on disk.
 * ---------------------------------------------------------------------------
 * Two rules the site now keeps, and this file is what enforces them:
 *
 *   1. The root is the landing page, as it always was. index.html is served
 *      at / and has no second address: /index.html and /index both redirect
 *      there, so the page a visitor lands on has exactly one URL.
 *
 *   2. No .html in any address. /dashboard serves dashboard.html, and
 *      /dashboard.html permanently redirects to /dashboard so old links,
 *      bookmarks and anything already indexed heal themselves rather than
 *      quietly serving a second copy of the page at a second URL.
 *
 * The list is generated rather than hand-kept, because a hand-kept list is one
 * a new page gets forgotten from — and the failure is silent, a 404 nobody
 * notices until a customer finds it. tests/clean-urls.test.js re-runs this
 * generator and fails the build if the committed file has drifted.
 *
 * Netlify matches _redirects top to bottom, first match wins, and the file
 * takes precedence over netlify.toml. Order below is deliberate:
 * the specific roots first, then the .html cleanups, then the rewrites.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const PUBLIC = path.join(__dirname, '..', 'public');
const OUT = path.join(PUBLIC, '_redirects');

// The landing page is the one file whose address is not its name: it is
// index.html on disk and simply / in an address.
const LANDING = 'index.html';
const LANDING_URL = '/';

// Addresses that no longer have a page behind them. A bookmark or an old link
// should land somewhere useful rather than on a 404. These live here rather
// than in netlify.toml so there is one file that decides where a URL goes.
const LEGACY = [
  ['/project-plan.html', '/dashboard'],   // Project Planner was removed
  ['/project-plan',      '/dashboard'],
  // /home was the landing page's address for one deploy, while the root
  // briefly belonged to the sign-in screen. Anything that saw it in that
  // window is sent to the root rather than to a 404.
  ['/home',              '/'],
];

function pages() {
  return fs.readdirSync(PUBLIC)
    .filter(f => f.endsWith('.html'))
    .sort();
}

function build() {
  const list = pages();
  const L = [];

  L.push('# ─────────────────────────────────────────────────────────────────');
  L.push('# GENERATED by scripts/build-routes.js — do not edit by hand.');
  L.push('# Re-run: node scripts/build-routes.js');
  L.push('# tests/clean-urls.test.js fails the build if this drifts.');
  L.push('# ─────────────────────────────────────────────────────────────────');
  L.push('');
  L.push('# The root is the landing page, and it is the only address for it:');
  L.push('# the file name and the bare /index both redirect here.');
  L.push(pad('/' + LANDING, 22) + pad(LANDING_URL, 22) + '301!');
  L.push(pad('/index', 22) + pad(LANDING_URL, 22) + '301!');
  L.push('# Addresses whose page is gone.');
  for (const [from, to] of LEGACY) L.push(pad(from, 22) + pad(to, 22) + '301!');
  L.push('');
  L.push('# Old .html addresses heal themselves. 301! forces the redirect even');
  L.push('# though the file exists at that path, which is the whole point.');
  for (const f of list) {
    if (f === LANDING) continue;                       // handled above
    const clean = '/' + f.replace(/\.html$/, '');
    L.push(pad('/' + f, 22) + pad(clean, 22) + '301!');
  }
  L.push('');
  L.push('# …and the clean address serves the file.');
  for (const f of list) {
    if (f === LANDING) continue;
    const clean = '/' + f.replace(/\.html$/, '');
    L.push(pad(clean, 22) + pad('/' + f, 22) + '200');
  }
  L.push('');
  return L.join('\n');
}

function pad(s, n) { return s + ' '.repeat(Math.max(1, n - s.length)); }

const next = build();
const prev = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';

if (require.main === module) {
  if (prev === next) {
    console.log('build-routes: already current — ' + pages().length + ' page(s)');
  } else {
    fs.writeFileSync(OUT, next);
    console.log('build-routes: written — ' + pages().length + ' page(s)');
  }
}

module.exports = { build, pages, LANDING, LANDING_URL, OUT };
