/* scripts/build-routes.js — generate public/_redirects from the pages on disk.
 * ---------------------------------------------------------------------------
 * Two rules the site now keeps, and this file is what enforces them:
 *
 *   1. The root IS the login. Typing cygenix.co.uk lands a visitor on the
 *      sign-in screen with the address bar still reading cygenix.co.uk — a
 *      200 rewrite, not a redirect, so there is no flash of another URL and
 *      nothing to see in the history. The marketing page keeps a home of its
 *      own at /home.
 *
 *   2. No .html in any address. /dashboard serves dashboard.html, and
 *      /dashboard.html permanently redirects to /dashboard so old links,
 *      bookmarks and anything already indexed heal themselves rather than
 *      quietly serving a second copy of the page at a second URL.
 *
 * The list is generated rather than hand-kept, because a hand-kept list is one
 * a new page gets forgotten from — and the failure is silent, a 404 nobody
 * notices until a customer finds it. tests/clean-urls.test.js re-runs this
 * generator and fails the build if the committed file has drifted.
 *
 * Netlify matches _redirects top to bottom, first match wins, and the file
 * takes precedence over netlify.toml. Order below is deliberate:
 * the specific roots first, then the .html cleanups, then the rewrites.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const PUBLIC = path.join(__dirname, '..', 'public');
const OUT = path.join(PUBLIC, '_redirects');

// The landing page is the one file whose clean name is not its file name: it
// is index.html on disk and /home in an address, because / belongs to login.
const LANDING = 'index.html';
const LANDING_URL = '/home';
const ROOT_PAGE = 'login.html';

// Addresses that no longer have a page behind them. A bookmark or an old link
// should land somewhere useful rather than on a 404. These live here rather
// than in netlify.toml so there is one file that decides where a URL goes.
const LEGACY = [
  ['/project-plan.html', '/dashboard'],   // Project Planner was removed
  ['/project-plan',      '/dashboard'],
];

function pages() {
  return fs.readdirSync(PUBLIC)
    .filter(f => f.endsWith('.html'))
    .sort();
}

function build() {
  const list = pages();
  const L = [];

  L.push('# ─────────────────────────────────────────────────────────────────');
  L.push('# GENERATED by scripts/build-routes.js — do not edit by hand.');
  L.push('# Re-run: node scripts/build-routes.js');
  L.push('# tests/clean-urls.test.js fails the build if this drifts.');
  L.push('# ─────────────────────────────────────────────────────────────────');
  L.push('');
  L.push('# The root is the sign-in screen. A 200 rewrite, so the address bar');
  L.push('# keeps reading cygenix.co.uk with nothing after it.');
  L.push(`/                     /${ROOT_PAGE}          200`);
  L.push('');
  L.push('# The marketing page, which used to be the root, keeps a home.');
  L.push(`${LANDING_URL}                 /${LANDING}          200`);
  L.push(`/${LANDING}           ${LANDING_URL}                301!`);
  L.push('/index                ' + LANDING_URL + '                301!');
  L.push('# Addresses whose page is gone.');
  for (const [from, to] of LEGACY) L.push(pad(from, 22) + pad(to, 22) + '301!');
  L.push('');
  L.push('# Old .html addresses heal themselves. 301! forces the redirect even');
  L.push('# though the file exists at that path, which is the whole point.');
  for (const f of list) {
    if (f === LANDING) continue;                       // handled above
    const clean = '/' + f.replace(/\.html$/, '');
    L.push(pad('/' + f, 22) + pad(clean, 22) + '301!');
  }
  L.push('');
  L.push('# …and the clean address serves the file.');
  for (const f of list) {
    if (f === LANDING) continue;
    const clean = '/' + f.replace(/\.html$/, '');
    L.push(pad(clean, 22) + pad('/' + f, 22) + '200');
  }
  L.push('');
  return L.join('\n');
}

function pad(s, n) { return s + ' '.repeat(Math.max(1, n - s.length)); }

const next = build();
const prev = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';

if (require.main === module) {
  if (prev === next) {
    console.log('build-routes: already current — ' + pages().length + ' page(s)');
  } else {
    fs.writeFileSync(OUT, next);
    console.log('build-routes: written — ' + pages().length + ' page(s)');
  }
}

module.exports = { build, pages, LANDING, LANDING_URL, ROOT_PAGE, OUT };
